services:
  backend:
    build:
      #Where dockerfile is
      context: ./back
      #Name of the file
      dockerfile: Dockerfile
    #This tells docker to watch the dir back and every change there map into docker back
    #notice that docker-compose and back are at the same dir, and docker_back is on the
    #machine running inside docker created in the dockerfile of this service
    volumes:
      - ./back:/docker_back
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BACKEND_HOST: ${BACKEND_HOST}
        NEXT_PUBLIC_BACKEND_PORT: ${BACKEND_PORT}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    volumes:
        #Where files are, I made a mistake and put /fronted and 
        #When run docker compose up an error tells me that do not where files are
      - ./front:/app

volumes:
  postgres_data:
