services:
  backend:
    build:
      #Where dockerfile is
      context: ./back
      #Name of the file
      dockerfile: Dockerfile
    #This tells docker to watch the dir back and every change there map into docker back
    #notice that docker-compose and back are at the same dir, and docker_back is on the
    #machine running inside docker created in the dockerfile of this service
    volumes:
      - ./back:/docker_back
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_EXTERNAL_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
