"""Change char len

Revision ID: 17578b5f7883
Revises: e29a976d3e17
Create Date: 2025-02-05 12:58:13.554910

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "17578b5f7883"
down_revision: Union[str, None] = "e29a976d3e17"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "item_table",
        "plain_text",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=300),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "item_table",
        "plain_text",
        existing_type=sa.String(length=300),
        type_=sa.VARCHAR(length=100),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
