"""Add kind col in stats table

Revision ID: 1a6a81b00faa
Revises: 91df02ac02a3
Create Date: 2025-02-15 20:22:21.739506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a6a81b00faa'
down_revision: Union[str, None] = '91df02ac02a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stats_table', sa.Column('kind', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stats_table', 'kind')
    # ### end Alembic commands ###
