"""Add location to the user table

Revision ID: 43da9cc73083
Revises: 9dd42a1c69b2
Create Date: 2025-03-31 15:52:29.963384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43da9cc73083'
down_revision: Union[str, None] = '9dd42a1c69b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_table', sa.Column('location_id', sa.Integer(), nullable=True))
    op.execute("UPDATE user_table SET location_id = 1 WHERE location_id IS NULL")
    op.create_foreign_key(None, 'user_table', 'location_table', ['location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_table', type_='foreignkey')
    op.drop_column('user_table', 'location_id')
    # ### end Alembic commands ###
