"""Add location and delivery date table

Revision ID: 47ae6c808476
Revises: 9c64d1d35142
Create Date: 2025-03-31 09:17:29.003498

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "47ae6c808476"
down_revision: Union[str, None] = "9c64d1d35142"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "location_table",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("country_name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("country_name"),
    )
    op.create_table(
        "delivery_dates_table",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column("delivery_date", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["item_table.id"],
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["location_table.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "item_location_delivery_association",
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column("delivery_date", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["item_table.id"],
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["location_table.id"],
        ),
        sa.PrimaryKeyConstraint("item_id", "location_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("item_location_delivery_association")
    op.drop_table("delivery_dates_table")
    op.drop_table("location_table")
    # ### end Alembic commands ###
