"""Add location to order table

Revision ID: 55501c343832
Revises: 03b3acf62f6c
Create Date: 2025-04-01 15:15:58.746775

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "55501c343832"
down_revision: Union[str, None] = "03b3acf62f6c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("order_table", sa.Column("location_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        None, "order_table", "location_table", ["location_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "order_table", type_="foreignkey")
    op.drop_column("order_table", "location_id")
    # ### end Alembic commands ###
