"""Remove id from meta data table, change primary key to name of field

Revision ID: 6eaa296e0f8a
Revises: dca507a505d5
Create Date: 2025-02-10 11:59:06.103840

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6eaa296e0f8a"
down_revision: Union[str, None] = "dca507a505d5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "meta_data_table", ["field_name"])
    op.drop_column("meta_data_table", "id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "meta_data_table",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
    )
    op.drop_constraint(None, "meta_data_table", type_="unique")
    # ### end Alembic commands ###
