"""Make description col more characters

Revision ID: 90195995df01
Revises: f60a9cd7c13a
Create Date: 2025-02-13 07:51:42.095265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90195995df01'
down_revision: Union[str, None] = 'f60a9cd7c13a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item_table', 'description',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=500),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item_table', 'description',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=300),
               nullable=True)
    # ### end Alembic commands ###
