"""delete hd path col

Revision ID: 9c64d1d35142
Revises: a60f1ae2ae0d
Create Date: 2025-03-26 08:55:57.940209

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9c64d1d35142"
down_revision: Union[str, None] = "a60f1ae2ae0d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("item_table", "imageHDPath")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "item_table",
        sa.Column(
            "imageHDPath", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
