"""Change delivery date type

Revision ID: 9dd42a1c69b2
Revises: 47ae6c808476
Create Date: 2025-03-31 09:42:40.139606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dd42a1c69b2'
down_revision: Union[str, None] = '47ae6c808476'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_dates_table', sa.Column('days_plus', sa.Integer(), nullable=False))
    op.drop_column('delivery_dates_table', 'delivery_date')
    op.add_column('item_location_delivery_association', sa.Column('days_plus', sa.Integer(), nullable=False))
    op.drop_column('item_location_delivery_association', 'delivery_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_location_delivery_association', sa.Column('delivery_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('item_location_delivery_association', 'days_plus')
    op.add_column('delivery_dates_table', sa.Column('delivery_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('delivery_dates_table', 'days_plus')
    # ### end Alembic commands ###
