"""Add description column to item table

Revision ID: a306ce54cc8e
Revises: a538b5ab56e0
Create Date: 2025-02-13 07:38:59.968565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a306ce54cc8e'
down_revision: Union[str, None] = 'a538b5ab56e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_table', sa.Column('description', sa.String(length=300), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_table', 'description')
    # ### end Alembic commands ###
