"""Add image url column to item table

Revision ID: a538b5ab56e0
Revises: a9286e0c0d1b
Create Date: 2025-02-12 16:00:20.118336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a538b5ab56e0'
down_revision: Union[str, None] = 'a9286e0c0d1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_table', sa.Column('imageUrl', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_table', 'imageUrl')
    # ### end Alembic commands ###
