"""Add image hd path

Revision ID: a60f1ae2ae0d
Revises: 305532e7245b
Create Date: 2025-03-26 08:08:34.018923

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a60f1ae2ae0d"
down_revision: Union[str, None] = "305532e7245b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "item_table", sa.Column("imageHDPath", sa.String(length=100), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("item_table", "imageHDPath")
    # ### end Alembic commands ###
