"""Delete image table

Revision ID: a9286e0c0d1b
Revises: 6eaa296e0f8a
Create Date: 2025-02-12 15:07:44.681838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9286e0c0d1b'
down_revision: Union[str, None] = '6eaa296e0f8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_table',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('full', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sprite', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('group', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='image_table_pkey')
    )
    # ### end Alembic commands ###
