"""Add new cols to user, emai, birthdate

Revision ID: bbfb5e02c020
Revises: c80a703e2cbb
Create Date: 2025-03-16 21:42:03.719854

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bbfb5e02c020"
down_revision: Union[str, None] = "c80a703e2cbb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_table", sa.Column("created", sa.Date(), nullable=False))
    op.add_column("user_table", sa.Column("last_singn", sa.Date(), nullable=False))
    op.add_column("user_table", sa.Column("gold_spend", sa.Integer(), nullable=False))
    op.add_column("user_table", sa.Column("current_gold", sa.Integer(), nullable=False))
    op.add_column(
        "user_table", sa.Column("email", sa.String(length=50), nullable=False)
    )
    op.add_column("user_table", sa.Column("birthdate", sa.Date(), nullable=False))
    op.create_unique_constraint(None, "user_table", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_table", type_="unique")
    op.drop_column("user_table", "birthdate")
    op.drop_column("user_table", "email")
    op.drop_column("user_table", "current_gold")
    op.drop_column("user_table", "gold_spend")
    op.drop_column("user_table", "last_singn")
    op.drop_column("user_table", "created")
    # ### end Alembic commands ###
