"""Add status and delivery date cols, change date to order date

Revision ID: c80a703e2cbb
Revises: bc3109504b1b
Create Date: 2025-03-04 09:10:53.415893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c80a703e2cbb'
down_revision: Union[str, None] = 'bc3109504b1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_table', sa.Column('delivery_date', sa.Date(), nullable=False))
    op.add_column('order_table', sa.Column('status', sa.String(length=30), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_table', 'status')
    op.drop_column('order_table', 'delivery_date')
    # ### end Alembic commands ###
