"""Second try to init sql alchemy tables

Revision ID: e29a976d3e17
Revises: 
Create Date: 2025-01-29 17:14:04.101421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e29a976d3e17'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gold_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('base_cost', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('sell', sa.Integer(), nullable=False),
    sa.Column('purchaseable', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full', sa.String(), nullable=False),
    sa.Column('sprite', sa.String(), nullable=False),
    sa.Column('group', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stats_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tags_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('item_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('plain_text', sa.String(length=100), nullable=False),
    sa.Column('image', sa.String(length=100), nullable=False),
    sa.Column('updated', sa.Boolean(), nullable=False),
    sa.Column('gold_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gold_id'], ['gold_table.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('item_stat_association',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('stat_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item_table.id'], ),
    sa.ForeignKeyConstraint(['stat_id'], ['stats_table.id'], ),
    sa.PrimaryKeyConstraint('item_id', 'stat_id')
    )
    op.create_table('item_tags_association',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('tags_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item_table.id'], ),
    sa.ForeignKeyConstraint(['tags_id'], ['tags_table.id'], ),
    sa.PrimaryKeyConstraint('item_id', 'tags_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_tags_association')
    op.drop_table('item_stat_association')
    op.drop_table('item_table')
    op.drop_table('tags_table')
    op.drop_table('stats_table')
    op.drop_table('image_table')
    op.drop_table('gold_table')
    # ### end Alembic commands ###
