global:
  scrape_interval: 15s # How often to scrape targets.

scrape_configs:
  - job_name: 'fastapi-app'
    static_configs:
      - targets: ['backend:8000']
        labels:
          instance: 'my-fastapi-instance'
