DEFAULT_ITEMS = [
    # Starter Items
    "Doran's Blade",
    "Doran's Ring",
    "Doran's Shield",
    "Cull",
    "Tear of the Goddess",
    "Dark Seal",
    "Corrupting Potion",
    "Refillable Potion",
    "Health Potion",
    "Total Biscuit of Everlasting Will",
    "Guardian's Blade",
    "Guardian's Hammer",
    "Guardian's Horn",
    "Guardian's Orb",
    "Guardian's Amulet",
    "Guardian's Shroud",

    # Basic Items
    "Amplifying Tome",
    "B. F. Sword",
    "Blasting Wand",
    "Cloak of Agility",
    "Cloth Armor",
    "Dagger",
    "Faerie Charm",
    "Long Sword",
    "Null-Magic Mantle",
    "Rejuvenation Bead",
    "Ruby Crystal",
    "Sapphire Crystal",
    "Sheen",
    "Vampiric Scepter",

    # Boots
    "Boots",
    "Berserker's Greaves",
    "Boots of Swiftness",
    "Ionian Boots of Lucidity",
    "Mercury's Treads",
    "Mobility Boots",
    "Plated Steelcaps",
    "Sorcerer's Shoes",

    # Epic Items
    "Caulfield's Warhammer",
    "Hexdrinker",
    "Kindlegem",
    "Phage",
    "Pickaxe",
    "Seeker's Armguard",
    "Spectre's Cowl",
    "Winged Moonplate",

    # Legendary Items
    "Black Cleaver",
    "Bloodthirster",
    "Dead Man's Plate",
    "Death's Dance",
    "Edge of Night",
    "Essence Reaver",
    "Frozen Heart",
    "Guardian Angel",
    "Infinity Edge",
    "Lord Dominik's Regards",
    "Maw of Malmortius",
    "Mercurial Scimitar",
    "Mortal Reminder",
    "Phantom Dancer",
    "Ravenous Hydra",
    "Runaan's Hurricane",
    "Serpent's Fang",
    "Sterak's Gage",
    "Stormrazor",
    "The Collector",
    "Titanic Hydra",
    "Umbral Glaive",
    "Void Staff",
    "Wit's End",
    "Zhonya's Hourglass",

    # Mythic Items
    "Crown of the Shattered Queen",
    "Divine Sunderer",
    "Duskblade of Draktharr",
    "Eclipse",
    "Everfrost",
    "Frostfire Gauntlet",
    "Goredrinker",
    "Hextech Rocketbelt",
    "Immortal Shieldbow",
    "Kraken Slayer",
    "Liandry's Anguish",
    "Locket of the Iron Solari",
    "Luden's Tempest",
    "Moonstone Renewer",
    "Night Harvester",
    "Prowler's Claw",
    "Riftmaker",
    "Shurelya's Battlesong",
    "Stridebreaker",
    "Sunfire Aegis",
    "Trinity Force",
    "Turbo Chemtank",

    # Consumables
    "Elixir of Iron",
    "Elixir of Sorcery",
    "Elixir of Wrath",
    "Control Ward",
    "Farsight Alteration",
    "Oracle Lens",
    "Stealth Ward"
]
