name: Backend test 
on: [push]

jobs:
  push-test-format:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.2'
          architecture: 'x64'
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('back/requirements.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-


      - name: Install dependencies
        working-directory: back
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.lock

      - name: Run unit test 
        working-directory: back 
        run: |
          python -m pytest -v test/

      - name: Format code
        working-directory: back
        run: |
          pip install black 
          black .
